import type { GuidedSettingsDraft, GuidedSettingsGroup } from '../domain/costCenterSettings';

export interface LogRootDiagnostic { root: string; status: 'ok' | 'missing' | 'unreadable'; filesCount: number; sessionsCount: number; latestActivity?: string; warnings: string[]; }
export interface GuidedSettingsPresentationModel { group: GuidedSettingsGroup; draft: GuidedSettingsDraft; errors: Record<string, string>; dirty: boolean; diagnostics: LogRootDiagnostic[]; }
type Escaper = (value: string) => string;

const fieldId = (key: string): string => `settings-${key.replace('.', '-')}`;
function numberField(key: string, label: string, value: number, errors: Record<string, string>, escape: Escaper): string {
  const invalid = errors[key] ? ` aria-invalid="true" aria-describedby="${fieldId(key)}-error"` : '';
  const message = errors[key] ? `<span id="${fieldId(key)}-error" class="field-error">${escape(errors[key])}</span>` : '';
  return `<div class="settings-field"><label for="${fieldId(key)}">${label}</label><input id="${fieldId(key)}" type="number" step="any" data-action="updateSettingField" data-key="${key}" data-value-type="number" value="${escape(String(value))}"${invalid}>${message}</div>`;
}
function checkbox(key: string, label: string, checked: boolean): string {
  return `<div class="settings-field"><input id="${fieldId(key)}" type="checkbox" data-action="updateSettingField" data-key="${key}"${checked ? ' checked' : ''}><label for="${fieldId(key)}">${label}</label></div>`;
}
function panel(group: GuidedSettingsGroup, active: GuidedSettingsGroup, content: string): string {
  return `<section id="settings-panel-${group}" role="tabpanel" aria-labelledby="settings-tab-${group}" data-settings-group="${group}"${group === active ? '' : ' hidden'}>${content}</section>`;
}

export function buildCostCenterSettings(model: GuidedSettingsPresentationModel, escape: Escaper): string {
  const { draft, errors } = model;
  const groups: Array<[GuidedSettingsGroup, string]> = [['budget', 'Budget'], ['display', 'Display'], ['dataSources', 'Data Sources'], ['notifications', 'Notifications']];
  const navigation = groups.map(([group, label]) => `<button type="button" role="tab" id="settings-tab-${group}" aria-controls="settings-panel-${group}" aria-selected="${group === model.group}" tabindex="${group === model.group ? '0' : '-1'}" data-action="setSettingsGroup" data-value="${group}">${label}</button>`).join('');
  const budget = panel('budget', model.group, `${numberField('budget.dayAmount', 'Daily budget (USD)', draft.budget.dayAmount, errors, escape)}${numberField('budget.weekAmount', 'Weekly budget (USD)', draft.budget.weekAmount, errors, escape)}${numberField('budget.monthAmount', 'Monthly budget (USD)', draft.budget.monthAmount, errors, escape)}${numberField('budget.warningPercent', 'Warning threshold (%)', draft.budget.warningPercent, errors, escape)}<p data-budget-preview aria-live="polite">Daily budget preview: $${draft.budget.dayAmount.toFixed(2)} · Weekly: $${draft.budget.weekAmount.toFixed(2)} · Monthly: $${draft.budget.monthAmount.toFixed(2)}</p>`);
  const select = (key: string, label: string, values: string[], selected: string): string => `<div class="settings-field"><label for="${fieldId(key)}">${label}</label><select id="${fieldId(key)}" data-action="updateSettingField" data-key="${key}"${errors[key] ? ` aria-invalid="true" aria-describedby="${fieldId(key)}-error"` : ''}>${values.map((value) => `<option value="${value}"${value === selected ? ' selected' : ''}>${value}</option>`).join('')}</select>${errors[key] ? `<span id="${fieldId(key)}-error" class="field-error">${escape(errors[key])}</span>` : ''}</div>`;
  const display = panel('display', model.group, `${checkbox('display.showSession', 'Show session cost', draft.display.showSession)}${checkbox('display.showWorkspace', 'Show workspace cost', draft.display.showWorkspace)}${checkbox('display.showBudget', 'Show budget', draft.display.showBudget)}${select('display.budgetPeriod', 'Budget period', ['day', 'week', 'month'], draft.display.budgetPeriod)}${select('display.defaultRange', 'Default range', ['today', '7d', '30d'], draft.display.defaultRange)}${checkbox('display.compareByDefault', 'Compare by default', draft.display.compareByDefault)}`);
  const diagnostics = model.diagnostics.map((item) => `<li><strong>${escape(item.root)}</strong>: ${item.status === 'ok' ? 'OK' : item.status === 'missing' ? 'Missing' : 'Unreadable'} · ${item.filesCount} files · ${item.sessionsCount} sessions${item.latestActivity ? ` · Latest activity ${escape(item.latestActivity)}` : ''}${item.warnings.map((warning) => `<p class="notice">${escape(warning)}</p>`).join('')}</li>`).join('');
  const textArea = (key: string, label: string, values: string[]): string => `<div class="settings-field"><label for="${fieldId(key)}">${label}</label><textarea id="${fieldId(key)}" data-action="updateSettingField" data-key="${key}" data-value-type="string-array"${errors[key] ? ` aria-invalid="true" aria-describedby="${fieldId(key)}-error"` : ''}>${escape(values.join('\n'))}</textarea>${errors[key] ? `<span id="${fieldId(key)}-error" class="field-error">${escape(errors[key])}</span>` : ''}</div>`;
  const dataSources = panel('dataSources', model.group, `${textArea('dataSources.logRoots', 'Log roots (one per line)', draft.dataSources.logRoots)}${textArea('dataSources.include', 'Included sources (one per line)', draft.dataSources.include)}<button type="button" data-action="checkData">Check data</button><ul>${diagnostics}</ul>`);
  const notifications = panel('notifications', model.group, `${checkbox('notifications.enabled', 'Enable budget notifications', draft.notifications.enabled)}${numberField('notifications.everyAmount', 'Notify every USD amount', draft.notifications.everyAmount, errors, escape)}${checkbox('notifications.thresholdSummary', 'Include threshold summary', draft.notifications.thresholdSummary)}<button type="button" data-action="testNotification">Test notification</button>`);
  return `<aside class="settings" aria-labelledby="settings-heading"><h2 id="settings-heading">Guided settings</h2><form data-dirty="${model.dirty}"><div role="tablist" aria-label="Settings groups">${navigation}</div>${budget}${display}${dataSources}${notifications}<div class="settings-actions"><button type="button" data-action="saveSettings"${model.dirty ? '' : ' disabled'}>Save</button><button type="button" data-action="discardSettings"${model.dirty ? '' : ' disabled'}>Discard</button><button type="button" data-action="resetSettingsGroup" data-value="${model.group}">Reset group</button><button type="button" data-action="openAdvancedSettings">Open advanced settings</button></div></form></aside>`;
}
